//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisOtomasyonu2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisUrunler
    {
        public string KullaniciAdi { get;set; }
        public int SiparisListesiId { get; set; }
        public int MusteriId { get; set; }
        public int SiparisUrunId { get; set; }
        public int UrunId { get; set; }
        public int UrunAdet { get; set; }
    
        public virtual SiparisListesiTable SiparisListesiTable { get; set; }
        public virtual UrunlerTable UrunlerTable { get; set; }
    }
}
