//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiparisOtomasyonu2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisListesiTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiparisListesiTable()
        {
            this.SiparisUrunler = new HashSet<SiparisUrunler>();
        }
    
        public int SiparisListesiId { get; set; }
        public int MusterilerId { get; set; }
        public double UrunToplamFiyat { get; set; }
        public System.DateTime SparisTarih { get; set; }
    
        public virtual MusterilerTable MusterilerTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisUrunler> SiparisUrunler { get; set; }
    }
}
